import { create } from 'zustand'
import { persist } from 'zustand/middleware'

const translations = {
  th: {
    workspace: 'พื้นที่ทำงาน',
    arena: 'สนามประลอง',
    settings: 'การตั้งค่า',
    newChat: 'สร้างแชทใหม่',
    history: 'ประวัติการแชทล่าสุด',
    hintDragchats: '💡 ลากแชทไปวางที่หมวดหมู่ด้านบน',
    all: 'ทั้งหมด',
    uncategorized: 'ไม่มีหมวดหมู่',
    categoryWork: 'งาน',
    categoryPersonal: 'ส่วนตัว',
    categoryResearch: 'วิจัย',
    search: 'ค้นหาแชท หรือ ข้อความ...',
    welcome: 'ยินดีต้อนรับกลับมา',
    subtitle: 'จัดการเอกสารและพูดคุยกับ AI ของคุณได้ที่นี่',
    historyDragHint: '💡 ลากแชทไปวางบนหมวดหมู่ได้',
    historyNoChatsTitle: 'ยังไม่มีประวัติการแชท',
    historyNoChatsSubtitle: 'กดปุ่ม {newChat} เพื่อเริ่มต้น',
    historyUntitledChat: 'แชทใหม่',
    historyEditTitle: 'แก้ไขชื่อ',
    historyDeleteChat: 'ลบแชท',
    historySave: 'บันทึก',
    historyCancel: 'ยกเลิก',
    historyDocumentsLabel: 'เอกสาร',
    historyMoving: 'กำลังย้าย...',
    historyDropOnCategory: 'วางที่หมวดหมู่ด้านบน',
    historyDraggingPrefix: 'กำลังย้าย',
    searchModalPlaceholder: 'ค้นหาข้อความหรือชื่อแชท...',
    searchModalTabChats: 'ชื่อแชท',
    searchModalTabMessages: 'ข้อความ',
    searchModalEmptyTitle: 'พิมพ์เพื่อค้นหาประวัติการแชท',
    searchModalEmptySubtitle: 'ค้นหาได้ทั้งชื่อแชทและเนื้อหาภายในแชท',
    searchModalNoResults: 'ไม่พบผลลัพธ์สำหรับ "{query}"',
    searchModalResults: 'ผลการค้นหา ({count} {unit})',
    searchModalChatsUnit: 'แชท',
    searchModalMatchedMessages: 'พบ {count} ข้อความ',
    searchModalUntitledChat: 'แชทที่ยังไม่ตั้งชื่อ',
    searchModalSenderUser: '🙂 คุณ',
    searchModalSenderAI: '🤖 AI Assistant',
    searchModalConnectionError: 'เกิดข้อผิดพลาดในการเชื่อมต่อ กรุณาลองใหม่อีกครั้ง',
    searchHintScroll: 'เลื่อนผลลัพธ์',
    searchHintOpenFirstResult: 'เปิดผลลัพธ์แรก',
    searchHintCloseSearch: 'ปิดหน้าค้นหา',
    workspaceSessionFallback: 'แชทใหม่',
    workspaceEditTitle: 'แก้ไขชื่อ',
    workspaceSave: 'บันทึก',
    workspaceCancel: 'ยกเลิก',
    workspaceChangeLanguage: 'เปลี่ยนภาษา',
    workspaceSwitchToLight: 'เปลี่ยนเป็นโหมดสว่าง',
    workspaceSwitchToDark: 'เปลี่ยนเป็นโหมดมืด',
    normalDocsTitle: 'จัดการเอกสาร',
    normalNoDocsInChat: 'ยังไม่มีเอกสารในแชทนี้',
    normalChatTitle: 'สนทนา',
    normalEmptyChatTitle: 'เริ่มพูดคุยกับ AI',
    normalEmptyChatSubtitle: 'อัปโหลดเอกสารด้านซ้าย จากนั้นพิมพ์คำถามของคุณที่นี่',
    normalInputPlaceholder: 'พิมพ์คำถามของคุณที่นี่...',
    normalKnowledgeBaseTitle: 'คลังความรู้',
    normalCollapsePanel: 'ย่อหน้าต่าง',
    normalExpandPanel: 'ขยายหน้าต่าง',
    normalUploadToViewInsights: 'อัปโหลดเอกสารเพื่อดูสรุปและ Mindmap',
    normalClickDocForDetailSummary: 'คลิกที่เอกสารเพื่อดูสรุปแบบละเอียด',
    normalTapForInsights: 'กดเพื่อดูข้อมูลเชิงลึก',
    uploadProcessingDefault: 'กำลังประมวลผลเอกสาร...',
    uploadProcessingHint: 'โปรดอย่าปิดหน้านี้ ระบบอาจใช้เวลาสักครู่',
    uploadDropzoneTitle: 'คลิกเพื่อเลือกไฟล์ PDF หรือลากไฟล์มาวาง',
    uploadDropzoneSubtitle: 'รองรับไฟล์ PDF ขนาดไม่เกิน 50 MB',
    uploadYourDocuments: 'เอกสารของคุณ',
    knowledgeTabSummary: 'สรุปเนื้อหา',
    knowledgeTabMindmap: 'แผนผัง Mindmap',
    knowledgeEmptyTitle: 'อัปโหลดเอกสารเพื่อสร้างข้อมูลเชิงลึก',
    knowledgeEmptySubtitle: 'สรุปเนื้อหาและ Mindmap จะแสดงที่นี่โดยอัตโนมัติ',
    citationSourceTitle: 'แหล่งที่มา (อ้างอิง)',
    citationPageLabel: 'หน้า',
    compareNeedSelectModels: 'กรุณาเลือกโมเดล A และ B',
    compareReceivedBothModels: 'ได้คำตอบจากทั้ง 2 โมเดล',
    compareFailed: 'ไม่สามารถเปรียบเทียบโมเดลได้',
    compareDocumentsTitle: 'เอกสาร',
    compareNoDocuments: 'ยังไม่มีเอกสาร',
    compareModelALeft: '📊 โมเดล A (ซ้าย)',
    compareModelBRight: '📊 โมเดล B (ขวา)',
    compareSelectModelA: 'เลือกโมเดล A',
    compareSelectModelB: 'เลือกโมเดล B',
    compareUsedByModelA: '(ใช้โมเดล A อยู่)',
    compareUsedByModelB: '(ใช้โมเดล B อยู่)',
    compareEmptyTitle: 'เปรียบเทียบโมเดล AI',
    compareEmptySubtitle: 'เลือกโมเดลทั้ง 2 แล้วส่งคำถามเดียวกันให้กับทั้งคู่',
    compareQuestionLabel: '👤 คำถาม:',
    compareModelAName: 'โมเดล A',
    compareModelBName: 'โมเดล B',
    compareNoAnswer: 'ไม่มีคำตอบ',
    compareVoteGood: 'ดี',
    compareVoteBad: 'แย่',
    compareInputPlaceholder: 'พิมพ์คำถามเพื่อเปรียบเทียบ...',
    arenaPageTitle: 'สนามประลองโมเดล',
    arenaPageSubtitle: 'เปรียบเทียบ AI สองโมเดลกับคำถามเดียวกันเพื่อหาคำตอบที่ดีที่สุด',
    arenaModelALabel: 'โมเดล A',
    arenaModelBLabel: 'โมเดล B',
    arenaInputPlaceholder: 'ถามคำถามเดียวกันกับทั้งสองโมเดล...',
    arenaEmptyTitle: 'เลือกสองโมเดลแล้วเริ่มประลอง!',
    arenaEmptySubtitle: 'ทั้งสองโมเดลจะตอบคำถามของคุณเคียงข้างกัน',
    settingsBackHome: 'กลับหน้าหลัก',
    settingsTitlePage: 'การตั้งค่า',
    settingsSubtitlePage: 'จัดการหมวดหมู่และการตั้งค่าต่างๆ',
    settingsCategoryTitle: 'จัดการหมวดหมู่',
    settingsCategorySubtitle: 'เพิ่ม แก้ไข และจัดการหมวดหมู่ของแชท',
    settingsAddCategory: 'เพิ่มหมวดหมู่',
    settingsCreateCategory: 'สร้างหมวดหมู่ใหม่',
    settingsEditCategory: 'แก้ไขหมวดหมู่',
    settingsCategoryName: 'ชื่อหมวดหมู่',
    settingsCategoryNamePlaceholder: 'เช่น งานบริษัท A',
    settingsIcon: 'ไอคอน',
    settingsColor: 'สี',
    settingsCreate: 'สร้าง',
    settingsNoCategories: 'ยังไม่มีหมวดหมู่ กดปุ่มเพิ่มหมวดหมู่เพื่อเริ่มต้น',
    settingsEdit: 'แก้ไข',
    settingsDelete: 'ลบ',
    settingsDeleteConfirm: 'ต้องการลบหมวดหมู่นี้หรือไม่?',
    uploadPdfOnly: 'อัปโหลดได้เฉพาะไฟล์ PDF เท่านั้น',
    uploadSizeLimit: 'ขนาดไฟล์ต้องไม่เกิน 50 MB',
    uploadEmbeddingProgress: 'กำลังฝังข้อมูลเอกสารลงสมอง AI...',
    uploadReadyToast: 'เอกสารพร้อมแล้ว! คุณสามารถพิมพ์ถามได้ทันที 💬',
    uploadSummaryReadyToast: 'AI สร้าง Summary และ Mindmap เสร็จสมบูรณ์! ✨',
    uploadProcessingError: 'เกิดข้อผิดพลาดในการประมวลผล',
    uploadServerDisconnected: 'ขาดการเชื่อมต่อกับ Server',
    uploadConnectionLost: 'การเชื่อมต่อขาดหาย',
    uploadFailed: 'อัปโหลดไม่สำเร็จ',
    chatModelResponseFailed: 'โมเดลตอบกลับไม่สำเร็จ',
    chatUnknownCause: 'ไม่ทราบสาเหตุ',
    chatConnectionFailed: 'ไม่สามารถเชื่อมต่อกับ Server ได้',
    chatAssistantError: '⚠️ เกิดข้อผิดพลาด: {message}',
    chatAssistantConnectionError: '⚠️ เกิดข้อผิดพลาดในการเชื่อมต่อ กรุณาลองใหม่อีกครั้ง',
    chatCompareFailed: 'การเปรียบเทียบล้มเหลว',
    chatCompareModelsFailed: 'การเปรียบเทียบโมเดลล้มเหลว',
    chatNoAnswerFromModel: 'ไม่ได้รับคำตอบจากโมเดลนี้',
    compareToggleToNormal: 'สลับเป็นโหมดปกติ',
    compareToggleToCompare: 'สลับเป็นโหมดเปรียบเทียบ',
    compareToggleCompare: 'เปรียบเทียบ',
    compareToggleNormal: 'ปกติ',
    chatPanelTitle: 'แชท AI',
    chatPanelEmptyTitle: 'เริ่มการสนทนา',
    chatPanelEmptySubtitle: 'ถามคำถามเกี่ยวกับเอกสาร หรือให้ AI ช่วยสรุปข้อมูลให้คุณ',
    chatPanelInputPlaceholder: 'พิมพ์ข้อความที่นี่...',
    thinkingTitle: 'กระบวนการคิดของ AI',
    thinkingTokens: '~{count} โทเคน',
    summaryNoData: 'ยังไม่มีข้อมูลสรุป กรุณาอัปโหลดเอกสารก่อน',
    summaryWordCount: '{count} คำ',
    summaryNoHelpfulData: 'ไม่มีข้อมูลสรุปที่ช่วย',
    mindmapNoData: 'ยังไม่มีข้อมูล Mindmap กรุณาอัปโหลดเอกสารก่อน',
    voteBetter: 'ดีกว่า',
    voteWorse: 'แย่กว่า',
    pdfOriginalDocument: 'เอกสารต้นฉบับ',
    pdfPreviewTitle: 'ตัวอย่าง PDF',
    // ... add more translations as needed
  },
  en: {
    workspace: 'Workspace',
    arena: 'Arena',
    settings: 'Settings',
    newChat: 'New Chat',
    history: 'Recent Chats',
    hintDragchats: '💡 Drag chats here to categorize them',
    all: 'All',
    uncategorized: 'Uncategorized',
    categoryWork: 'Work',
    categoryPersonal: 'Personal',
    categoryResearch: 'Research',
    search: 'Search chats or messages...',
    welcome: 'Welcome Back',
    subtitle: 'Manage documents and chat with AI here',
    historyDragHint: '💡 Drag chats and drop onto a category',
    historyNoChatsTitle: 'No chat history yet',
    historyNoChatsSubtitle: 'Click {newChat} to get started',
    historyUntitledChat: 'New Chat',
    historyEditTitle: 'Edit title',
    historyDeleteChat: 'Delete chat',
    historySave: 'Save',
    historyCancel: 'Cancel',
    historyDocumentsLabel: 'documents',
    historyMoving: 'Moving...',
    historyDropOnCategory: 'Drop onto a category above',
    historyDraggingPrefix: 'Moving',
    searchModalPlaceholder: 'Search messages or chat titles...',
    searchModalTabChats: 'Chat Titles',
    searchModalTabMessages: 'Messages',
    searchModalEmptyTitle: 'Start typing to search chat history',
    searchModalEmptySubtitle: 'Search both chat titles and message content',
    searchModalNoResults: 'No results found for "{query}"',
    searchModalResults: 'Results ({count} {unit})',
    searchModalChatsUnit: 'chats',
    searchModalMatchedMessages: 'Found {count} messages',
    searchModalUntitledChat: 'Untitled Chat',
    searchModalSenderUser: '🙂 You',
    searchModalSenderAI: '🤖 AI Assistant',
    searchModalConnectionError: 'Connection error occurred. Please try again.',
    searchHintScroll: 'Scroll results',
    searchHintOpenFirstResult: 'Open first result',
    searchHintCloseSearch: 'Close search',
    workspaceSessionFallback: 'Chat Session',
    workspaceEditTitle: 'Edit title',
    workspaceSave: 'Save',
    workspaceCancel: 'Cancel',
    workspaceChangeLanguage: 'Change language',
    workspaceSwitchToLight: 'Switch to light mode',
    workspaceSwitchToDark: 'Switch to dark mode',
    normalDocsTitle: 'Document Manager',
    normalNoDocsInChat: 'No documents in this chat yet',
    normalChatTitle: 'Conversation',
    normalEmptyChatTitle: 'Start chatting with AI',
    normalEmptyChatSubtitle: 'Upload documents on the left, then type your question here',
    normalInputPlaceholder: 'Type your question here...',
    normalKnowledgeBaseTitle: 'Knowledge Base',
    normalCollapsePanel: 'Collapse panel',
    normalExpandPanel: 'Expand panel',
    normalUploadToViewInsights: 'Upload documents to view summary and mindmap',
    normalClickDocForDetailSummary: 'Click a document to view a detailed summary',
    normalTapForInsights: 'Click to view insights',
    uploadProcessingDefault: 'Processing document...',
    uploadProcessingHint: 'Please do not close this page. This may take a moment.',
    uploadDropzoneTitle: 'Click to select a PDF file or drag and drop it here',
    uploadDropzoneSubtitle: 'Supports PDF files up to 50 MB',
    uploadYourDocuments: 'Your documents',
    knowledgeTabSummary: 'Summary',
    knowledgeTabMindmap: 'Mindmap',
    knowledgeEmptyTitle: 'Upload documents to generate insights',
    knowledgeEmptySubtitle: 'Summary and mindmap will appear here automatically',
    citationSourceTitle: 'Sources (Citations)',
    citationPageLabel: 'Page',
    compareNeedSelectModels: 'Please select Model A and Model B',
    compareReceivedBothModels: 'Received responses from both models',
    compareFailed: 'Unable to compare models',
    compareDocumentsTitle: 'Documents',
    compareNoDocuments: 'No documents yet',
    compareModelALeft: '📊 Model A (Left)',
    compareModelBRight: '📊 Model B (Right)',
    compareSelectModelA: 'Select Model A',
    compareSelectModelB: 'Select Model B',
    compareUsedByModelA: '(currently used by Model A)',
    compareUsedByModelB: '(currently used by Model B)',
    compareEmptyTitle: 'Compare AI Models',
    compareEmptySubtitle: 'Select both models and send the same question to each',
    compareQuestionLabel: '👤 Question:',
    compareModelAName: 'Model A',
    compareModelBName: 'Model B',
    compareNoAnswer: 'No answer',
    compareVoteGood: 'Good',
    compareVoteBad: 'Bad',
    compareInputPlaceholder: 'Type a question to compare...',
    arenaPageTitle: 'Model Arena',
    arenaPageSubtitle: 'Compare two AI models on the same question to find the best answer',
    arenaModelALabel: 'Model A',
    arenaModelBLabel: 'Model B',
    arenaInputPlaceholder: 'Ask the same question to both models...',
    arenaEmptyTitle: 'Pick two models and start the battle!',
    arenaEmptySubtitle: 'Both models will answer your question side by side',
    settingsBackHome: 'Back to home',
    settingsTitlePage: 'Settings',
    settingsSubtitlePage: 'Manage categories and other preferences',
    settingsCategoryTitle: 'Category Management',
    settingsCategorySubtitle: 'Create, edit, and organize chat categories',
    settingsAddCategory: 'Add category',
    settingsCreateCategory: 'Create new category',
    settingsEditCategory: 'Edit category',
    settingsCategoryName: 'Category name',
    settingsCategoryNamePlaceholder: 'e.g. Company A work',
    settingsIcon: 'Icon',
    settingsColor: 'Color',
    settingsCreate: 'Create',
    settingsNoCategories: 'No categories yet. Click add category to get started',
    settingsEdit: 'Edit',
    settingsDelete: 'Delete',
    settingsDeleteConfirm: 'Do you want to delete this category?',
    uploadPdfOnly: 'Please upload a PDF file only.',
    uploadSizeLimit: 'File size must be under 50 MB.',
    uploadEmbeddingProgress: 'Embedding document into AI memory...',
    uploadReadyToast: 'Document is ready! You can start asking now 💬',
    uploadSummaryReadyToast: 'AI finished generating Summary and Mindmap! ✨',
    uploadProcessingError: 'Processing error occurred',
    uploadServerDisconnected: 'Disconnected from server',
    uploadConnectionLost: 'Connection lost',
    uploadFailed: 'Upload failed',
    chatModelResponseFailed: 'Model response failed',
    chatUnknownCause: 'Unknown cause',
    chatConnectionFailed: 'Cannot connect to server',
    chatAssistantError: '⚠️ Error: {message}',
    chatAssistantConnectionError: '⚠️ Connection error occurred. Please try again.',
    chatCompareFailed: 'Comparison failed',
    chatCompareModelsFailed: 'Model comparison failed',
    chatNoAnswerFromModel: 'No answer from this model',
    compareToggleToNormal: 'Switch to normal mode',
    compareToggleToCompare: 'Switch to compare mode',
    compareToggleCompare: 'COMPARE',
    compareToggleNormal: 'NORMAL',
    chatPanelTitle: 'AI Chat',
    chatPanelEmptyTitle: 'Start a conversation',
    chatPanelEmptySubtitle: 'Ask about your documents or let AI summarize for you',
    chatPanelInputPlaceholder: 'Type your message here...',
    thinkingTitle: 'AI Thinking Process',
    thinkingTokens: '~{count} tokens',
    summaryNoData: 'No summary data yet. Please upload a document first.',
    summaryWordCount: '{count} words',
    summaryNoHelpfulData: 'No helpful summary data',
    mindmapNoData: 'No mindmap data yet. Please upload a document first.',
    voteBetter: 'Better',
    voteWorse: 'Worse',
    pdfOriginalDocument: 'Original Document',
    pdfPreviewTitle: 'PDF Preview',
  }
}

export const useLanguageStore = create(
  persist(
    (set, get) => ({
      lang: 'th',
      t: (key) => {
        const langInfo = translations[get().lang]
        if (!langInfo) return key
        return langInfo[key] || key
      },
      toggleLanguage: () => set((state) => ({ lang: state.lang === 'th' ? 'en' : 'th' })),
      setLanguage: (lang) => set({ lang })
    }),
    {
      name: 'rag-language',
    }
  )
)
